
language: python
sudo: false

env:
  - LUA="lua 5.1"

before_install:
  - pip install hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PATH:$PWD/here/bin

install:
  - luarocks install luacov-coveralls
  - luarocks install luafilesystem

script:
  - lua tests/testAllCompile.lua
  - lua tests/testPenlightRequire.lua
